
version: 0.2
phases:
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${FIPS_REPOSITORY_URI}
      - echo Building the Docker image...
      - PATCH_TAG=${TAG_NAME#"v"} # major.minor.patch
      - MINOR_TAG=${PATCH_TAG%.*} # major.minor
      - MAJOR_TAG=${MINOR_TAG%.*} # major
      - docker build -t ${FIPS_REPOSITORY_URI}:${PATCH_TAG} -t ${FIPS_REPOSITORY_URI}:${MINOR_TAG} -t ${FIPS_REPOSITORY_URI}:${MAJOR_TAG} .
      - docker image push --all-tags  ${FIPS_REPOSITORY_URI}
  post_build:
    commands:
      - echo Build completed!
      - printf '{"tag":"%s"}' $TAG_NAME > build.json
