version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build --target test -t ds-python .
      - run:
          name: Verify build completed
          command: docker run ds-python /bin/bash -c "echo BUILDS OK"
      - run:
          name: Run tests
          command: docker run ds-python /test_image.py -vv
