version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container
          command: docker build -t ds-python .
      - run:
          name: Verify build completed
          command: docker run ds-python /bin/bash -c "echo BUILDS OK"
      - run:
          name: Check that scipy links to OpenBLAS
          command: docker run ds-python python -c "from scipy.linalg import _fblas"
      - run:
          name: Verify that numpy and matplotlib function
          command: docker run ds-python python -c "import numpy, os; import matplotlib.pyplot as plt; x = numpy.arange(100); y = numpy.sin(x); plt.plot(x, y);"
      - run:
          name: Check that seaborn is installed
          command: docker run ds-python python -c "import seaborn"
      - run:
          name: Check that numpy imports from bash shell
          command: docker run -t ds-python /bin/bash -c "python -c 'import numpy'"
      - run:
          name: Verify that numpy does not link to MKL
          command: docker run ds-python python -c "from numpy.distutils import system_info; assert system_info.get_info('mkl') == {}"
      - run:
          name: Run numpy unit tests
          command: docker run ds-python python -c "import numpy; numpy.test()"
      - run:
          name: List packages installed from conda-forge
          command: docker run ds-python /bin/bash -c "conda list|grep conda-forge"
      - run:
          name: Check that the expected number of packages come from conda-forge
          command: docker run ds-python /bin/bash -c "conda list|grep -c conda-forge|python -c \"import sys; actual_count = int(sys.stdin.readlines()[0]); expected_count = 11; assert actual_count == expected_count, 'There should be %d conda-forge packages, but there are actually %d.' % (expected_count, actual_count)\""
